In [2]:
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Eager execution is: {}".format(tf.executing_eagerly()))
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.0.0-alpha0
Eager execution is: True
Keras version: 2.2.4-tf


## Running on GPU or CPU

In [3]:
var = tf.Variable([3, 3])

if tf.test.is_gpu_available(): 
    print('Running on GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else: 
    print('Running on CPU')

Running on CPU


## Declaring eager variables

In [4]:
t0 = 24 # python variable
t1 = tf.Variable(42) # rank 0 tensor
t2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) #rank 3 tensor
t0, t1, t2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

In [5]:
f64 = tf.Variable(89, dtype = tf.float64)
f64.dtype

tf.float64

In [7]:
f1 = tf.Variable(89.)
f1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [8]:
m_o_l = tf.constant(42)
m_o_l

<tf.Tensor: id=49, shape=(), dtype=int32, numpy=42>

## Shaping a tensor

In [9]:
t2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) # tensor variable
print(t2.shape)

(2, 2, 3)


In [10]:
r1 = tf.reshape(t2,[2,6]) # 2 rows 6 cols
r2 = tf.reshape(t2,[1,12]) # 1 rows 12 cols
r1

<tf.Tensor: id=60, shape=(2, 6), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]], dtype=float32)>

## Ranking (dimensions) of a tensor

In [11]:
tf.rank(t2)

<tf.Tensor: id=66, shape=(), dtype=int32, numpy=3>

## Specifying an element of a tensor

In [12]:
t3 = t2[1, 0, 2] # slice 1, row 0, column 2
t3

<tf.Tensor: id=72, shape=(), dtype=float32, numpy=8.0>

## Casting a tensor to a NumPy/Python variable

In [13]:
print(t2.numpy())

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


In [14]:
s =  tf.size(input=t2).numpy()
s

12

## Specifying element-wise primitive tensor operations

In [15]:
t2*t2

<tf.Tensor: id=81, shape=(2, 2, 3), dtype=float32, numpy=
array([[[  0.,   1.,   4.],
        [  9.,  16.,  25.]],

       [[ 36.,  49.,  64.],
        [ 81., 100., 121.]]], dtype=float32)>

## Broadcasting

In [16]:
t4 = t2*4
print(t4)

tf.Tensor(
[[[ 0.  4.  8.]
  [12. 16. 20.]]

 [[24. 28. 32.]
  [36. 40. 44.]]], shape=(2, 2, 3), dtype=float32)


## Transposing TensorFlow and matrix multiplication

In [17]:
u = tf.constant([[3,4,3]]) 
v = tf.constant([[1,2,1]])
tf.matmul(u, tf.transpose(a=v))

<tf.Tensor: id=91, shape=(1, 1), dtype=int32, numpy=array([[14]], dtype=int32)>

In [19]:
j = tf.cast(tf.constant(4.9), dtype=tf.int32) # 4j
j

<tf.Tensor: id=96, shape=(), dtype=int32, numpy=4>

## Declaring ragged tensors

A ragged tensor is a tensor with one or more ragged dimensions. Ragged dimensions are dimensions that have slices that may have different lengths.

In [20]:
ragged =tf.ragged.constant([[5, 2, 6, 1], [], [4, 10, 7], [8], [6,7]])
print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>
tf.Tensor([5 2 6 1], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 4 10  7], shape=(3,), dtype=int32)
tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)


## Useful tensorflow operations

In [22]:
x = [1,3,5,7,11]
y = 5
s = tf.math.squared_difference(x,y)
s

<tf.Tensor: id=238, shape=(5,), dtype=int32, numpy=array([16,  4,  0,  4, 36], dtype=int32)>

In [23]:
numbers = tf.constant([[4., 5.], [7., 3.]])

<tf.Tensor: id=242, shape=(), dtype=float32, numpy=4.75>

In [25]:
tf.reduce_mean(input_tensor=numbers)

<tf.Tensor: id=248, shape=(), dtype=float32, numpy=4.75>

In [24]:
tf.reduce_mean(input_tensor=numbers, axis=0, keepdims=True)

<tf.Tensor: id=245, shape=(1, 2), dtype=float32, numpy=array([[5.5, 4. ]], dtype=float32)>