In [2]:
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Eager execution is: {}".format(tf.executing_eagerly()))
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.0.0-alpha0
Eager execution is: True
Keras version: 2.2.4-tf


## Running on GPU or CPU

In [3]:
var = tf.Variable([3, 3])

if tf.test.is_gpu_available(): 
    print('Running on GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else: 
    print('Running on CPU')

Running on CPU


## Declaring eager variables

In [4]:
t0 = 24 # python variable
t1 = tf.Variable(42) # rank 0 tensor
t2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) #rank 3 tensor
t0, t1, t2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

In [5]:
f64 = tf.Variable(89, dtype = tf.float64)
f64.dtype

tf.float64

In [7]:
f1 = tf.Variable(89.)
f1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [8]:
m_o_l = tf.constant(42)
m_o_l

<tf.Tensor: id=49, shape=(), dtype=int32, numpy=42>

## Shaping a tensor

In [9]:
t2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) # tensor variable
print(t2.shape)

(2, 2, 3)


In [10]:
r1 = tf.reshape(t2,[2,6]) # 2 rows 6 cols
r2 = tf.reshape(t2,[1,12]) # 1 rows 12 cols
r1

<tf.Tensor: id=60, shape=(2, 6), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]], dtype=float32)>

## Ranking (dimensions) of a tensor

In [11]:
tf.rank(t2)

<tf.Tensor: id=66, shape=(), dtype=int32, numpy=3>

## Specifying an element of a tensor

In [12]:
t3 = t2[1, 0, 2] # slice 1, row 0, column 2
t3

<tf.Tensor: id=72, shape=(), dtype=float32, numpy=8.0>

## Casting a tensor to a NumPy/Python variable

In [13]:
print(t2.numpy())

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


In [14]:
s =  tf.size(input=t2).numpy()
s

12

## Specifying element-wise primitive tensor operations

In [15]:
t2*t2

<tf.Tensor: id=81, shape=(2, 2, 3), dtype=float32, numpy=
array([[[  0.,   1.,   4.],
        [  9.,  16.,  25.]],

       [[ 36.,  49.,  64.],
        [ 81., 100., 121.]]], dtype=float32)>

## Broadcasting

In [16]:
t4 = t2*4
print(t4)

tf.Tensor(
[[[ 0.  4.  8.]
  [12. 16. 20.]]

 [[24. 28. 32.]
  [36. 40. 44.]]], shape=(2, 2, 3), dtype=float32)


## Transposing TensorFlow and matrix multiplication

In [17]:
u = tf.constant([[3,4,3]]) 
v = tf.constant([[1,2,1]])
tf.matmul(u, tf.transpose(a=v))

<tf.Tensor: id=91, shape=(1, 1), dtype=int32, numpy=array([[14]], dtype=int32)>

In [19]:
j = tf.cast(tf.constant(4.9), dtype=tf.int32) # 4j
j

<tf.Tensor: id=96, shape=(), dtype=int32, numpy=4>

## Declaring ragged tensors

A ragged tensor is a tensor with one or more ragged dimensions. Ragged dimensions are dimensions that have slices that may have different lengths.

In [20]:
ragged =tf.ragged.constant([[5, 2, 6, 1], [], [4, 10, 7], [8], [6,7]])
print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>
tf.Tensor([5 2 6 1], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 4 10  7], shape=(3,), dtype=int32)
tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)


## Useful tensorflow operations

In [22]:
x = [1,3,5,7,11]
y = 5
s = tf.math.squared_difference(x,y)
s

<tf.Tensor: id=238, shape=(5,), dtype=int32, numpy=array([16,  4,  0,  4, 36], dtype=int32)>

In [23]:
numbers = tf.constant([[4., 5.], [7., 3.]])

<tf.Tensor: id=242, shape=(), dtype=float32, numpy=4.75>

In [25]:
tf.reduce_mean(input_tensor=numbers)

<tf.Tensor: id=248, shape=(), dtype=float32, numpy=4.75>

In [8]:
numbers = tf.constant([[4., 5.], [7., 3.]])
tf.reduce_mean(input_tensor=numbers, axis=0)

<tf.Tensor: id=19, shape=(2,), dtype=float32, numpy=array([5.5, 4. ], dtype=float32)>

In [9]:
numbers = tf.constant([[4., 5.], [7., 3.]])
tf.reduce_mean(input_tensor=numbers, axis=0, keepdims=True)

<tf.Tensor: id=23, shape=(1, 2), dtype=float32, numpy=array([[5.5, 4. ]], dtype=float32)>

In [12]:
numbers = tf.constant([[4., 5.], [7., 3.]])
tf.reduce_mean(input_tensor=numbers, axis=1)

<tf.Tensor: id=35, shape=(2,), dtype=float32, numpy=array([4.5, 5. ], dtype=float32)>

In [13]:
numbers = tf.constant([[4., 5.], [7., 3.]])
tf.reduce_mean(input_tensor=numbers, axis=1, keepdims=True)

<tf.Tensor: id=39, shape=(2, 1), dtype=float32, numpy=
array([[4.5],
       [5. ]], dtype=float32)>

## Generating tensors filled with random values

In [14]:
ran = tf.random.normal(shape = (3,2), mean=10.0, stddev=2.0)
print(ran)

tf.Tensor(
[[ 8.806503 10.29445 ]
 [ 8.745884 10.478781]
 [10.677351 11.253087]], shape=(3, 2), dtype=float32)


In [15]:
tf.random.uniform(shape = (2,4),  minval=0, maxval=None, dtype=tf.float32, seed=None,  name=None)

<tf.Tensor: id=54, shape=(2, 4), dtype=float32, numpy=
array([[0.98323774, 0.40994108, 0.1304717 , 0.7850783 ],
       [0.32309508, 0.8220775 , 0.35015476, 0.31639576]], dtype=float32)>

## practical example of random values

In [16]:
dice1 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
dice2 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
 
 # We may add dice1 and dice2 since they share the same shape and size.
dice_sum = dice1 + dice2
 
 # We've got three separate 10x1 matrices. To produce a single
 # 10x3 matrix, we'll concatenate them along dimension 1.
resulting_matrix = tf.concat(values=[dice1, dice2, dice_sum], axis=1)
 
print(resulting_matrix)

tf.Tensor(
[[6 2 8]
 [3 6 9]
 [4 5 9]
 [2 3 5]
 [3 6 9]
 [3 3 6]
 [4 1 5]
 [1 1 2]
 [1 4 5]
 [1 1 2]], shape=(10, 3), dtype=int32)


## Finding the indices of the largest and smallest element

In [19]:
t5 = tf.constant([2, 11, 5, 42, 7, 19, -6, -11, 29])
print(t5)
i = tf.argmax(input=t5)
print('index of max; ', i)
print('Max element: ', t5[i].numpy())
i = tf.argmin(input=t5, axis=0).numpy()
print('index of min: ', i)
print('Min element: ',t5[i].numpy())

tf.Tensor([  2  11   5  42   7  19  -6 -11  29], shape=(9,), dtype=int32)
index of max;  tf.Tensor(3, shape=(), dtype=int64)
Max element:  42
index of min:  7
Min element:  -11


In [24]:
t6 = tf.reshape(t5, [3,3])
print(t6)
i = tf.argmax(input=t6,axis=0).numpy() # max arg down rows
print('indices of max down rows; ', i)
i = tf.argmin(input=t6,axis=0).numpy() # min arg down rows
print('indices of min down rows ; ',i)
print(t6)
i = tf.argmax(input=t6,axis=1).numpy() # max arg across cols
print('indices of max across cols: ',i)
i = tf.argmin(input=t6,axis=1).numpy() # min arg across cols
print('indices of min across cols: ',i)

tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)
indices of max down rows;  [1 0 2]
indices of min down rows ;  [2 2 0]
tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)
indices of max across cols:  [1 0 2]
indices of min across cols:  [0 1 1]


## Saving and restoring tensor values using a checkpoint

In [25]:
variable = tf.Variable([[1,3,5,7],[11,13,17,19]])
checkpoint= tf.train.Checkpoint(var=variable)
save_path = checkpoint.save('./vars')
variable.assign([[0,0,0,0],[0,0,0,0]])
variable
checkpoint.restore(save_path)
print(variable)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [11, 13, 17, 19]], dtype=int32)>


## Using tf.function
tf.function is a function that will take a Python function and return a TensorFlow graph. The advantage of this is that graphs can apply optimizations and exploit parallelism in the Python function

In [27]:
def f1(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 2, 5) + y**2)

f2 = tf.function(f1)

x = tf.constant([4., -5.])
y = tf.constant([2., 3.])

# f1 and f2 return the same value, but f2 executes as a TensorFlow graph

assert f1(x,y).numpy() == f2(x,y).numpy()

## Keras, a High-Level API for TensorFlow 2

Keras, which is a high-level API for TensorFlow 2.  Keras has become extremely popular for fast prototyping, for building and training deep learning models, and for research and production. Keras is a very rich API; it supports eager execution and data pipelines, and other features.

Keras include built-in support for multi-GPU data parallelism, and also the fact that Keras models can be turned into TensorFlow Estimators and trained on clusters of GPUs on Google Cloud

It's maintained independently of TensorFlow, although TensorFlow does have a full implementation of Keras in the tf.keras module. The implementation has TensorFlow-specific augmentations, including support for eager execution, by default.

In [28]:
import tensorflow as tf
print(tf.keras.__version__)

2.2.4-tf


In [29]:
from tensorflow.keras import backend as K
const = K.constant([[42,24],[11,99]], dtype=tf.float16, shape=[2,2])
const

<tf.Tensor: id=254, shape=(2, 2), dtype=float16, numpy=
array([[42., 24.],
       [11., 99.]], dtype=float16)>

## Keras models

### The first way to create a Sequential model


In [30]:
mnist = tf.keras.datasets.mnist
(train_x,train_y), (test_x, test_y) = mnist.load_data()

epochs=10
batch_size = 32 # 32 is default in fit method but specify anyway

train_x, test_x = tf.cast(train_x/255.0, tf.float32), tf.cast(test_x/255.0, tf.float32)
train_y, test_y = tf.cast(train_y,tf.int64),tf.cast(test_y,tf.int64) 

model1 = tf.keras.models.Sequential([
 tf.keras.layers.Flatten(),
 tf.keras.layers.Dense(512,activation=tf.nn.relu),
 tf.keras.layers.Dropout(0.2),
 tf.keras.layers.Dense(10,activation=tf.nn.softmax)
])

optimiser = tf.keras.optimizers.Adam()
model1.compile (optimizer= optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

model1.fit(train_x, train_y, batch_size=batch_size, epochs=epochs)

model1.evaluate(test_x, test_y)


11493376/11490434 [==============================] - 3s 0us/step
Epoch 1/10
60000/60000 [==============================] - 5s 79us/sample - loss: 0.2210 - accuracy: 0.9351
Epoch 2/10
60000/60000 [==============================] - 4s 71us/sample - loss: 0.0970 - accuracy: 0.9703
Epoch 3/10
60000/60000 [==============================] - 5s 80us/sample - loss: 0.0682 - accuracy: 0.9786
Epoch 4/10
60000/60000 [==============================] - 5s 77us/sample - loss: 0.0530 - accuracy: 0.9828
Epoch 5/10
60000/60000 [==============================] - 8s 135us/sample - loss: 0.0440 - accuracy: 0.9854
Epoch 6/10
60000/60000 [==============================] - 4s 65us/sample - loss: 0.0381 - accuracy: 0.9873
Epoch 7/10
60000/60000 [==============================] - 4s 69us/sample - loss: 0.0318 - accuracy: 0.9894
Epoch 8/10
60000/60000 [==============================] - 9s 144us/sample - loss: 0.0259 - accuracy: 0.9918
Epoch 9/10
60000/60000 [==============================] - 6s 106us/sample - l

[0.0691536510806247, 0.9822]

## The second way to create a Sequential model

In [32]:
model2 = tf.keras.models.Sequential();
model2.add(tf.keras.layers.Flatten())
model2.add(tf.keras.layers.Dense(512, activation='relu'))
model2.add(tf.keras.layers.Dropout(0.2))
model2.add(tf.keras.layers.Dense(10,activation=tf.nn.softmax))

model2.compile (optimizer= tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy', 
 metrics = ['accuracy'])

model2.fit(train_x, train_y, batch_size=batch_size, epochs=epochs)

model2.evaluate(test_x, test_y)

Epoch 1/10
60000/60000 [==============================] - 4s 64us/sample - loss: 0.2194 - accuracy: 0.9356
Epoch 2/10
60000/60000 [==============================] - 11s 185us/sample - loss: 0.0962 - accuracy: 0.9699
Epoch 3/10
60000/60000 [==============================] - 5s 90us/sample - loss: 0.0706 - accuracy: 0.9788
Epoch 4/10
60000/60000 [==============================] - 3s 56us/sample - loss: 0.0551 - accuracy: 0.9823
Epoch 5/10
60000/60000 [==============================] - 3s 56us/sample - loss: 0.0435 - accuracy: 0.9855
Epoch 6/10
60000/60000 [==============================] - 6s 101us/sample - loss: 0.0376 - accuracy: 0.9873
Epoch 7/10
60000/60000 [==============================] - 6s 108us/sample - loss: 0.0307 - accuracy: 0.9901
Epoch 8/10
60000/60000 [==============================] - 9s 146us/sample - loss: 0.0277 - accuracy: 0.9909
Epoch 9/10
60000/60000 [==============================] - 6s 98us/sample - loss: 0.0259 - accuracy: 0.9912
Epoch 10/10
10000/10000 [=======

[0.07390079730178914, 0.9822]

## The Keras functional API

In [34]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist
(train_x,train_y), (test_x, test_y) = mnist.load_data()
train_x, test_x = train_x/255.0, test_x/255.0
epochs=10

inputs = tf.keras.Input(shape=(28,28)) # Returns a 'placeholder' tensor

x = tf.keras.layers.Flatten()(inputs)
x = tf.keras.layers.Dense(512, activation='relu',name='d1')(x)
x = tf.keras.layers.Dropout(0.2)(x)

predictions = tf.keras.layers.Dense(10, activation=tf.nn.softmax, name='d2')(x)

model3 = tf.keras.Model(inputs=inputs, outputs=predictions)

optimiser = tf.keras.optimizers.Adam()
model3.compile (optimizer= optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

model3.fit(train_x, train_y, batch_size=32, epochs=epochs)

model3.evaluate(test_x, test_y)

Epoch 1/10
60000/60000 [==============================] - 4s 71us/sample - loss: 0.2228 - accuracy: 0.9333
Epoch 2/10
60000/60000 [==============================] - 4s 65us/sample - loss: 0.0965 - accuracy: 0.9699
Epoch 3/10
60000/60000 [==============================] - 4s 70us/sample - loss: 0.0689 - accuracy: 0.9788
Epoch 4/10
60000/60000 [==============================] - 4s 72us/sample - loss: 0.0543 - accuracy: 0.9826
Epoch 5/10
60000/60000 [==============================] - 4s 63us/sample - loss: 0.0452 - accuracy: 0.9856
Epoch 6/10
60000/60000 [==============================] - 4s 66us/sample - loss: 0.0362 - accuracy: 0.9879
Epoch 7/10
60000/60000 [==============================] - 6s 96us/sample - loss: 0.0312 - accuracy: 0.9896
Epoch 8/10
60000/60000 [==============================] - 7s 118us/sample - loss: 0.0283 - accuracy: 0.9903
Epoch 9/10
60000/60000 [==============================] - 4s 64us/sample - loss: 0.0253 - accuracy: 0.9917
Epoch 10/10
10000/10000 [===========

[0.07052516256404633, 0.9823]

## Subclassing the Keras Model class

In [37]:
class MyModel(tf.keras.Model):
 def __init__(self, num_classes=10):
   super(MyModel, self).__init__()
   self.inputs = tf.keras.Input(shape=(28,28)) # Returns a placeholder tensor
   self.x0 = tf.keras.layers.Flatten()
   self.x1 = tf.keras.layers.Dense(512, activation='relu',name='d1')
   self.x2 = tf.keras.layers.Dropout(0.2)
   self.predictions = tf.keras.layers.Dense(10,activation=tf.nn.softmax, name='d2')

 def call(self, inputs):
 # This is where to define your forward pass
 # using the layers previously defined in `__init__`
   x = self.x0(self.inputs)
   x = self.x1(x)
   x = self.x2(x) 
   return self.predictions(x)


In [46]:
model4 = MyModel()
model4.compile (optimizer= tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy', metrics = ['accuracy'])
model4.fit(train_x, train_y, batch_size=32, epochs=10)
model4.evaluate(test_x, test_y)

TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.

## Using data pipelines

Data may also be passed into the fit method as a tf.data.Dataset() iterator

In [52]:
batch_size = 32
buffer_size = 10000

train_dataset = tf.data.Dataset.from_tensor_slices((train_x, train_y)).batch(32).shuffle(10000)

train_dataset = train_dataset.map(lambda x, y: (tf.image.random_flip_left_right(x), y))
train_dataset = train_dataset.repeat()

test_dataset = tf.data.Dataset.from_tensor_slices((test_x, test_y)).batch(batch_size).shuffle(10000)
test_dataset = train_dataset.repeat()

steps_per_epoch = len(train_x)//batch_size # required because of the repeat on the dataset
optimiser = tf.keras.optimizers.Adam()
model3.compile (optimizer= optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])
model3.fit(train_dataset, epochs=10, steps_per_epoch=10)

Epoch 1/10
10/10 [==============================] - 1s 53ms/step - loss: 5.0150 - accuracy: 0.5813
Epoch 2/10
10/10 [==============================] - 0s 3ms/step - loss: 2.3393 - accuracy: 0.7500
Epoch 3/10
10/10 [==============================] - 0s 3ms/step - loss: 2.9338 - accuracy: 0.6062
Epoch 4/10
10/10 [==============================] - 0s 4ms/step - loss: 1.6812 - accuracy: 0.7437
Epoch 5/10
10/10 [==============================] - 0s 3ms/step - loss: 1.0459 - accuracy: 0.8000
Epoch 6/10
10/10 [==============================] - 0s 4ms/step - loss: 1.1154 - accuracy: 0.7750
Epoch 7/10
10/10 [==============================] - 0s 3ms/step - loss: 1.0910 - accuracy: 0.8031
Epoch 8/10
10/10 [==============================] - 0s 4ms/step - loss: 0.8977 - accuracy: 0.8031
Epoch 9/10
10/10 [==============================] - 0s 3ms/step - loss: 0.8256 - accuracy: 0.8250
Epoch 10/10
10/10 [==============================] - 0s 5ms/step - loss: 0.5918 - accuracy: 0.8500


## Saving and loading Keras models

In [54]:
model3.save('./model_name.h5')

In [55]:
from tensorflow.keras.models import load_model
new_model = load_model('./model_name.h5')

model3.save_weights('./model_weights.h5')
model3.load_weights('./model_weights.h5')

## Keras datasets

The following datasets are available from within Keras: boston_housing, cifar10, cifar100, fashion_mnist, imdb, mnist, and reuters.

They are all accessed with the load_data() function. For example, to load the fashion_mnist dataset, use the following:

In [56]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()


4423680/4422102 [==============================] - 1s 0us/step


## ANN Technologies Using TensorFlow 2

Using NumPy arrays with datasets

## One shot Iterator

In [1]:
import tensorflow as tf
import numpy as np 

num_items = 11
num_list1 = np.arange(num_items)
num_list2 = np.arange(num_items,num_items*2)



In [3]:
num_list1_dataset = tf.data.Dataset.from_tensor_slices(num_list1)
iterator = tf.compat.v1.data.make_one_shot_iterator(num_list1_dataset)
for item in num_list1_dataset:
    num = iterator.get_next().numpy()
    print(num)

0
1
2
3
4
5
6
7
8
9
10


## One shot Iterator with batch

In [4]:
num_list1_dataset = tf.data.Dataset.from_tensor_slices(num_list1).batch(3, drop_remainder = False)
iterator = tf.compat.v1.data.make_one_shot_iterator(num_list1_dataset)
for item in num_list1_dataset:
    num = iterator.get_next().numpy()
    print(num)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10]


## One shot Iterator with Zipped dataset

In [5]:
dataset1 = [1,2,3,4,5]
dataset2 = ['a','e','i','o','u']
dataset1 = tf.data.Dataset.from_tensor_slices(dataset1)
dataset2 = tf.data.Dataset.from_tensor_slices(dataset2)
zipped_datasets = tf.data.Dataset.zip((dataset1, dataset2))
iterator = tf.compat.v1.data.make_one_shot_iterator(zipped_datasets)
for item in zipped_datasets:
    num = iterator.get_next()
    print(num)

(<tf.Tensor: id=96, shape=(), dtype=int32, numpy=1>, <tf.Tensor: id=97, shape=(), dtype=string, numpy=b'a'>)
(<tf.Tensor: id=102, shape=(), dtype=int32, numpy=2>, <tf.Tensor: id=103, shape=(), dtype=string, numpy=b'e'>)
(<tf.Tensor: id=108, shape=(), dtype=int32, numpy=3>, <tf.Tensor: id=109, shape=(), dtype=string, numpy=b'i'>)
(<tf.Tensor: id=114, shape=(), dtype=int32, numpy=4>, <tf.Tensor: id=115, shape=(), dtype=string, numpy=b'o'>)
(<tf.Tensor: id=120, shape=(), dtype=int32, numpy=5>, <tf.Tensor: id=121, shape=(), dtype=string, numpy=b'u'>)


## One shot Iterator with Concatenate datasets

In [7]:
ds1 = tf.data.Dataset.from_tensor_slices([1,2,3,5,7,11,13,17])
ds2 = tf.data.Dataset.from_tensor_slices([19,23,29,31,37,41])
ds3 = ds1.concatenate(ds2)
print(ds3)
iterator = tf.compat.v1.data.make_one_shot_iterator(ds3)
for i in range(14):
  num = iterator.get_next()
  print(num)

<ConcatenateDataset shapes: (), types: tf.int32>
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(11, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)
tf.Tensor(17, shape=(), dtype=int32)
tf.Tensor(19, shape=(), dtype=int32)
tf.Tensor(23, shape=(), dtype=int32)
tf.Tensor(29, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)
tf.Tensor(37, shape=(), dtype=int32)
tf.Tensor(41, shape=(), dtype=int32)


## CSV example 1

In [8]:
filename = ["./size_1000.csv"]
record_defaults = [tf.float32] * 2 # two required float columns
dataset = tf.data.experimental.CsvDataset(filename, record_defaults, header=True, select_cols=[1,2])
for item in dataset:
  print(item)

NotFoundError: ./size_1000.csv; No such file or directory [Op:IteratorGetNextSync]

## CSV example 2

In [9]:
#file Chapter_2.ipynb
filename = "mycsvfile.txt"
record_defaults = [tf.float32, tf.constant([0.0], dtype=tf.float32), tf.int32,]
dataset = tf.data.experimental.CsvDataset(filename, record_defaults, header=False, select_cols=[1,2,3])
for item in dataset:
  print(item)

NotFoundError: mycsvfile.txt; No such file or directory [Op:IteratorGetNextSync]

## CSV example 3

In [11]:
filename = "file1.txt"
record_defaults = [tf.float32, tf.float32, tf.string ,]
dataset = tf.data.experimental.CsvDataset(filename, record_defaults, header=False)
for item in dataset:
    print(item[0].numpy(), item[1].numpy(),item[2].numpy().decode() ) 
# decode as string is in binary format.

NotFoundError: file1.txt; No such file or directory [Op:IteratorGetNextSync]

## TFRecords

Another popular choice for storing data is the TFRecord format. This is a binary file format. For large files, it is a good choice because binary files take up less disc space, take less time to copy, and can be read very efficiently from the disc.

Because a TFRecord file is a sequence of binary strings, its structure must be specified prior to saving so that it can be properly written and subsequently read back. 

TensorFlow has two structures for this, tf.train.Example and tf.train.SequenceExample. 

What you have to do is store each sample of your data in one of these structures, then serialize it, and use tf.python_io.TFRecordWriter to save it to disk.

In [12]:
import tensorflow as tf
import numpy as np

data=np.array([10.,11.,12.,13.,14.,15.])

def npy_to_tfrecords(fname,data):
    writer = tf.io.TFRecordWriter(fname)
    feature={}
    feature['data'] = tf.train.Feature(float_list=tf.train.FloatList(value=data))
    example = tf.train.Example(features=tf.train.Features(feature=feature))
    serialized = example.SerializeToString()
    writer.write(serialized)
    writer.close()

npy_to_tfrecords("./myfile.tfrecords",data)

In [14]:
dataset = tf.data.TFRecordDataset("./myfile.tfrecords")

def parse_function(example_proto):
    keys_to_features = {'data':tf.io.FixedLenSequenceFeature([], dtype = tf.float32, allow_missing = True) }
    parsed_features = tf.io.parse_single_example(serialized=example_proto, features=keys_to_features)
    return parsed_features['data']

dataset = dataset.map(parse_function)
iterator = tf.compat.v1.data.make_one_shot_iterator(dataset)
# array is retrieved as one item
item = iterator.get_next()
print(item)
print(item.numpy())
print(item[2].numpy())

tf.Tensor([10. 11. 12. 13. 14. 15.], shape=(6,), dtype=float32)
[10. 11. 12. 13. 14. 15.]
12.0


## TFRecord example 2

In [15]:
filename = './students.tfrecords'
data = {
            'ID': 61553,
            'Name': ['Jones', 'Felicity'],
            'Scores': [45.6, 97.2] 
        }

ID = tf.train.Feature(int64_list=tf.train.Int64List(value=[data['ID']]))

Name = tf.train.Feature(bytes_list=tf.train.BytesList(value=[n.encode('utf-8') for n in data['Name']]))

Scores = tf.train.Feature(float_list=tf.train.FloatList(value=data['Scores']))

example = tf.train.Example(features=tf.train.Features(feature={'ID': ID, 'Name': Name, 'Scores': Scores }))

writer = tf.io.TFRecordWriter(filename)
writer.write(example.SerializeToString())
writer.close()

In [16]:
dataset = tf.data.TFRecordDataset("./students.tfrecords")

def parse_function(example_proto):
    keys_to_features = {'ID':tf.io.FixedLenFeature([], dtype = tf.int64),
                       'Name':tf.io.VarLenFeature(dtype = tf.string),
                        'Scores':tf.io.VarLenFeature(dtype = tf.float32)
                       }
    parsed_features = tf.io.parse_single_example(serialized=example_proto, features=keys_to_features)
    return parsed_features["ID"], parsed_features["Name"],parsed_features["Scores"]

In [17]:
dataset = dataset.map(parse_function)

iterator = tf.compat.v1.data.make_one_shot_iterator(dataset)
item = iterator.get_next()
# record is retrieved as one item
print(item)

(<tf.Tensor: id=309, shape=(), dtype=int64, numpy=61553>, <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x7fcb500486d8>, <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x7fcb247f5630>)


In [19]:
print("ID: ",item[0].numpy())
name = item[1].values.numpy()
name1= name[0].decode()
name2 = name[1].decode('utf8')
print("Name:",name1,",",name2)
print("Scores: ",item[2].values.numpy())

ID:  61553
Name: Jones , Felicity
Scores:  [45.6 97.2]


## One-hot encoding

One-hot encoding (OHE) is where a tensor is constructed from the data labels with a 1 in each of the elements corresponding to a label's value, and 0 everywhere else; that is, one of the bits in the tensor is hot (1)

In [20]:
y = 5
y_train_ohe = tf.one_hot(y, depth=10).numpy() 
print(y, "is ",y_train_ohe,"when one-hot encoded with a depth of 10")

5 is  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] when one-hot encoded with a depth of 10


In [24]:
import tensorflow as tf
from tensorflow.python.keras.datasets import fashion_mnist
tf.executing_eagerly()
width, height, = 28,28
n_classes = 10

# load the dataset
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
split = 50000
#split feature training set into training and validation sets
(y_train, y_valid) = y_train[:split], y_train[split:]

# one-hot encode the labels using TensorFlow. 
# then convert back to numpy for display 

y_train_ohe = tf.one_hot(y_train, depth=n_classes).numpy() 
y_valid_ohe = tf.one_hot(y_valid, depth=n_classes).numpy()
y_test_ohe = tf.one_hot(y_test, depth=n_classes).numpy()

# show difference between the original label and a one-hot-encoded label

i=5
print(y_train[i]) # 'ordinary' number value of label at index i=5 is 2
# 2
# note the difference between the index of 5 and the label at that index which is 2
print(y_train_ohe[i]) # 
# 0. 0. 1. 0. 0.0 .0 .0. 0. 0.

2
2
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


## Layers

The fundamental data structure used by ANNs is the layer, and many interconnected layers make up a complete ANN

## Dense (fully connected) layer
A dense layer is a fully connected layer. This means that all neurons in the previous layer are connected to all neurons in the next layer. In a dense network, all layers are dense

In [ ]:
layer = tf.keras.layers.Dense(n)

## Convolutional layer

A convolutional layer is a layer where the neurons in a layer are grouped into small patches by the use of a filter, which is usually square, and created by sliding the filter over the layer. Each patch is convolved, that is, multiplied and summed by the filter. Convolutional nets or ConvNets for short, have proved themselves to be very good at image recognition and manipulation

In [26]:
seqtial_Net = tf.keras.Sequential([tf.keras.layers.Conv2D(1, (1, 1), strides = 1, padding='valid')])

## Max pooling layer

A max pooling layer takes the maximum value within its window as the window slides over the layer, in much the same way as a convolution takes place.


In [29]:
tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=None, padding='valid', data_format=None)
layer = tf.keras.layers.MaxPooling2D()

## Batch normalization layer and dropout layer

Batch normalization is a layer that takes its inputs and outputs the same number of outputs with activations that have zero mean and unit variance, as this has been found to be beneficial to learning. Batch normalization regulates the activations so that they neither become vanishingly small nor explosively big, both of which situations prevent the network from learning.

Dropout layer is a layer where a certain percentage of the neurons are randomly turned off during training (not during inference). This forces the network to become better at generalizing since individual neurons are discouraged from becoming specialized with respect to their inputs.


In [30]:
tf.keras.layers.BatchNormalization(axis=-1, momentum=0.99, epsilon=0.001, center=True, scale=True, beta_initializer='zeros', gamma_initializer='ones', moving_mean_initializer='zeros', moving_variance_initializer='ones', beta_regularizer=None, gamma_regularizer=None, beta_constraint=None, gamma_constraint=None)
layer = tf.keras.layers.BatchNormalization()

In [31]:
rate=0.5
tf.keras.layers.Dropout(rate, noise_shape=None, seed=None)
layer = tf.keras.layers.Dropout(rate = 0.5)


## Softmax layer

A softmax layer is a layer where the activation of each output unit corresponds to the probability that the output unit matches a given label. The output neuron with the highest activation value is, therefore, the prediction of the net. It is used when the classes being learned are mutually exclusive, so that the probabilities output by the softmax layer total 1.

In [32]:
tf.keras.layers.Dense(10,activation=tf.nn.softmax)

## Activation functions

It is important to note that neural nets have non-linear activation functions, that is, the functions that are applied to the sum of the weighted inputs to a neuron. Linear activation units are not able to map input layers to output layers in all but trivial neural net models.

There are a number of activation functions in common use, including sigmoid, tanh, ReLU, and leaky ReLU. A good summary, together with diagrams of these functions, may be found here: https://towardsdatascience.com/activation-functions-neural-networks-1cbd9f8d91d6.

### Creating the model

There are four methods for creating our ANN model using Keras:

Method 1: Arguments passed to tf.keras.Sequential
Method 2: Use of the .add method of tf.keras.Sequential
Method 3: Use of the Keras functional API
Method 4: By subclassing the tf.keras.Model object

## Gradient calculations for gradient descent algorithms

One of TenorFlow's great strengths is its ability to automatically compute gradients for use in gradient descent algorithms, which, of course, are a vital part of most machine learning models. TensorFlow offers a number of methods for gradient calculations.

tf.GradientTape: Context records computations so that you can call tf.gradient() to get the gradients of any tensor computed while recording with respect to any trainable variable

tfe.gradients_function(): Takes a function (say f()) and returns a gradient function (say fg()) that can compute the gradients of the outputs of f() with respect to the parameters of f() or a subset of them

tfe.implicit_gradients(): This is very similar, but fg() computes the gradients of the outputs of f() with regard to all trainable variables that these outputs depend on

tfe.implicit_value_and_gradients(): This is almost identical, but fg() also returns the output of the function, f()

In [33]:
# by default, you can only call tape.gradient once in a GradientTape context
weight1 = tf.Variable(2.0)

def weighted_sum(x1):
   return weight1 * x1

with tf.GradientTape() as tape:
   sum = weighted_sum(7.)
   [weight1_grad] = tape.gradient(sum, [weight1])
    
print(weight1_grad.numpy()) # 7 , weight1*x diff w.r.t. weight1 is x, 7.0, also see below.

7.0


In [34]:
# if you need to call tape.gradient() more than once
# use GradientTape(persistent=True) 
weight1 = tf.Variable(2.0)
weight2 = tf.Variable(3.0)
weight3 = tf.Variable(5.0)

def weighted_sum(x1, x2, x3):
    return weight1*x1 + weight2*x2 + weight3*x3

with tf.GradientTape(persistent=True) as tape:
   sum = weighted_sum(7.,5.,6.)

[weight1_grad] = tape.gradient(sum, [weight1])
[weight2_grad] = tape.gradient(sum, [weight2])
[weight3_grad] = tape.gradient(sum, [weight3])

print(weight1_grad.numpy()) #7.0
print(weight2_grad.numpy()) #5.0
print(weight3_grad.numpy()) #6.0

7.0
5.0
6.0


## Loss functions

A loss function (that is, an error measurement) is a necessary part of the training of an ANN. It is a measure of the extent to which the calculated output of a network during training differs from its required output